### ISSUE TITLE
hasura_connect and hasura_cache_interceptor don't match the version

### ISSUE THREAD

**Issue by kim-mini6** [Flutterando/hasura_connect#104]
flutter pub get error

[my_app] flutter pub get
Running "flutter pub get" in my_app...                     
Because hasura_cache_interceptor >=1.0.0-dev.5 depends on hasura_connect ^3.0.0 and my_app depends on hasura_connect ^4.0.0+2, hasura_cache_interceptor >=1.0.0-dev.5 is forbidden.
So, because my_app depends on hasura_cache_interceptor ^1.0.0-dev.5, version solving failed.
pub get failed (1; So, because my_app depends on hasura_cache_interceptor ^1.0.0-dev.5, version solving failed.)
exit code 1

**Comment by elvizcaino** [comment]
Please resolve this!

**Comment by Bwolfs2** [comment]
Fixed on the lastest version, if the error persist please reopen the issue.
