### ISSUE TITLE
meta ^1.8.0

### ISSUE THREAD

**Issue by HudsonAfonso** [Flutterando/hasura_connect#107]
flutter 3.0.5-stable depende do meta: 1.7.0

Because every version of flutter from sdk depends on meta 1.7.0 and hasura_connect >=4.0.0+3 depends on meta ^1.8.0, flutter from sdk is incompatible with hasura_connect >=4.0.0+3.
So, because pay depends on both hasura_connect 4.0.0+3 and flutter from sdk, version solving failed.

**Comment by HudsonAfonso** [comment]
@tauamendonca as you can see in your picture, in MASTER flutter depends on meta 1.8.0, however if you check the link tag 3.0.5, it depends on 1.7.0

https://github.com/flutter/flutter/blob/3.0.5/packages/flutter/pubspec.yaml

@Bwolfs2 please verify

**Comment by Bwolfs2** [comment]
Fixed, i reduce to 1.7.0 
Thanks o/
