### ISSUE TITLE
bump either_dart from ^0.1.3 to ^0.2.0

### ISSUE THREAD

**Issue by HudsonAfonso** [Flutterando/hasura_connect#114]
Bump either_dart from ^0.1.3 to ^0.2.0

>## [0.2.0] - Update Future[Either]
>
>Updated to support `FutureOr<T>` instead of `Future<T>`:
>  * Either: 
>    * thenAsync
>    * thenLeftAsync
>    * mapAsync
>    * mapLeftAsync
>  * Future[Either]:
>    * thenRight
>    * thenLeft
>
>Updated to support `FutureOr<T>` instead of `T`:
>  * Future[Either]:
>    * mapRight
>    * mapLeft
>
>Mark deprecated (not delete):
> * Future[Either].thenRightSync
> * Future[Either].thenLeftSync
> * Future[Either].mapRightAsync
> * Future[Either].mapLeftAsync
>
>The following methods were not needed after `FutureOr` support, so they are marked Deprecated.

**Comment by Bwolfs2** [comment]
Updated

**Comment by HudsonAfonso** [comment]
awaiting release
