### ISSUE TITLE
Erro Hive nova versão

### ISSUE THREAD

**Issue by wesleyviana** [Flutterando/hasura_connect#13]
Hello guys ,  segue erro que esta acontecendo.

 [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: 'package:hive/src/binary/frame.dart': Failed assertion: line 20 pos 13: '(key is int && key >= 0 && key < 4294967295) ||
E/flutter ( 1624):                 (key is String && key.length <= 255)': Unsupported key
E/flutter ( 1624): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:40:39)
E/flutter ( 1624): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter ( 1624): #2      new Frame (package:hive/src/binary/frame.dart:20:13)
E/flutter ( 1624): #3      BoxImpl.putAll (package:hive/src/box/box_impl.dart:51:18)
E/flutter ( 1624): #4      BoxBase.put (package:hive/src/box/box_base.dart:92:45)
E/flutter ( 1624): #5      LocalStorageHasura.put (package:hasura_connect/src/services/local_storage_hasura.dart:65:15)
E/flutter ( 1624): <asynchronous suspension>
E/flutter ( 1624): #6      HydratedSubject._persistValue (package:hasura_connect/src/utils/hydrated.dart:125:25)
E/flutter ( 1624): <asynchronous suspension>
E/flutter ( 1624): #7      HydratedSubject.onAdd (package:hasura_connect/src/utils/hydrated.dart:78:5)
E/flutter ( 1624): #8      Subject._add (package:rxdart/src/subjects/subject.dart:135:5)
E/flutter ( 1624): #9      Subject.add (package:rxdart/src/subjects/subject.dart:131:5)
E/flutter ( 1624): #10     new SnapshotData.<anonymous closure> (package:hasura_connect/src/snapshot/snapshot_data.dart:52:21)

**Comment by jacobaraujo7** [comment]
troquei para o SharedPreferences
