### ISSUE TITLE
'stream' isn't defined for the class 'Snapshot'.

### ISSUE THREAD

**Issue by JacquesMarques** [Flutterando/hasura_connect#15]
Hi,
I has a project with HasuraConnect 0.2.0 and when I try update to 1.0.0 it give and error:
```
    Snapshot snapshot = connection.subscription(query, variables: {"id": id});
    return snapshot.stream.map(
      (jsonList) => Order.fromJsonList(jsonList["data"]["orders"]),
    );
```

The getter 'stream' isn't defined for the class 'Snapshot'.
Try importing the library that defines 'stream', correcting the name to the name of an existing getter, or defining a getter or field named 'stream'.

How can fix this?
Thanks,

**Comment by jacobaraujo7** [comment]
rename snapshot.stream.map to snapshot.map
