### ISSUE TITLE
Improve error messages on posts

### ISSUE THREAD

**Issue by JacquesMarques** [Flutterando/hasura_connect#17]
Hi,
I'm having a problem when execute a mutation code, it always returns the message: HasuraError: connection error, but when I went to check I realized that the error was caused by a wrongly named variable that I passed in the function call. but instead of telling me what the problem was, the plugin only says that there was a connection error which was not really.
If you can fix this I appreciate it.

Thanks

**Comment by natarajnattu** [comment]
Hi @JacquesMarques ,

See this commit, change the line in your flutter external packages:
https://github.com/Flutterando/hasura_connect/pull/21/commits/bf464e158554a6a88a32e378e2b924ccb7e960b2

you can able to handle messages when error comes :)

**Comment by JacquesMarques** [comment]
Hi @natarajnattu,

Thanks for your help, but the problem is not in this line, the problem is in the lines below:

```
    try {
      var response =
          await client.post(url, body: jsonString, headers: headersLocal);
      Map json = jsonDecode(response.body);

      if (response.statusCode == 200) {
        if (hash != null) {
          await _localStorageMutation.remove(hash);
        }
        if (json.containsKey("errors")) {
          throw HasuraError.fromJson(json["errors"][0]);
        }
        return json;
      } else {
        throw HasuraError("connection error", null);
      }
    } catch (r) {
      throw HasuraError("connection error", null);
    } finally {
      client.close();
    }
```

In the two else below it throw exception with only the message: "connection error" and does not show the correct error message, could it be that way:

```
      } else {
        throw HasuraError("connection error, statusCode: ${response.statusCode}", null);
      }
    } catch (r) {
      throw HasuraError("connection error: ${r.toString()}", null);
    } finally {
      client.close();
    }
```
or something better.

Thanks

**Comment by natarajnattu** [comment]
Hi @JacquesMarques ,

I didn't do this commit to this repo for Error class
But look at this:

Original File:

```
class HasuraError implements Exception {
  final String message;
  final Extensions extensions;

  HasuraError(this.message, this.extensions);

  factory HasuraError.fromJson(Map json) {
    return HasuraError(
        json["message"], Extensions.fromJson(json["extensions"]));
  }

  @override
  String toString() {
    return "HasuraError: $message";
  }
}

class Extensions {
  final dynamic path;
  final dynamic code;

  Extensions(this.path, this.code);

  factory Extensions.fromJson(Map json) {
    return Extensions(json["path"], json["code"]);
  }

  @override
  String toString() {
    return "path: $path, code: $code";
  }
}
```

Here

```
factory HasuraError.fromJson(Map json) {
    return HasuraError(
        **json["message"]**, Extensions.fromJson(json["extensions"]));
  }
```

In My case im getting 

`{extensions: {path: $.selectionSet.insert_material.args.objects, code: constraint-violation}, message: Uniqueness violation. duplicate key value violates unique constraint "material_hsn_key"}`

**json["message"]** contains special characters like **"** inside it.

May be it is the reason i din't checked it yet,
