### ISSUE TITLE
What's the different with https://github.com/zino-app/graphql-flutter ? 

### ISSUE THREAD

**Issue by muhajirdev** [Flutterando/hasura_connect#24]
When should I use hasura_connect and when should I use graphql-flutter?

**Comment by natarajnattu** [comment]
Hi @muhajirdev ,

if your server is configured with https://hasura.io/ hasura_connect is better than other one.
implementation is simple compared to graphql-flutter trust me im using this for a month ;)
subscriptions is very easy to setup in hasura_connect
and also hasura server error messages can be handled.

**Comment by arpitjacob** [comment]
Hi can you give an example of using provider with subscriptions, subscriptions seems to return the same data and changing the variables don't seem to make a difference.
