### ISSUE TITLE
Method addHeader() is not working

### ISSUE THREAD

**Issue by blinkn** [Flutterando/hasura_connect#25]
Hi, I would like to report that `hasura_connect` on version **1.0.5**, the method **addHeader()** is not working properly.

Steps to Reproduce:

1. Create a flutter new project
2. Add `hasura_connect` to dependencies on pubspec.yaml
3. Do the following in the _incrementCounter() method of _MyHomePageState:

```dart
String query = "query MyQuery {company {name}}";
HasuraConnect connect = HasuraConnect('http://localhost:8080/v1/graphql');
connect.addHeader('x-hasura-admin-secret', 'secret');
connect.query(query).then((results) {
  print(results);
});
```

4. Then try to run the application on emulator/device.
5. Click on the FAB to increment the counter.
6. The error is thrown

> ════════ Exception caught by gesture >═══════════════════════════════════════════
>The following NoSuchMethodError was thrown while handling a gesture:
>The method '[]=' was called on null.
>Receiver: null
>Tried calling: []=("x-hasura-admin-secret", "secret")
>
>When the exception was thrown, this was the stack
>#0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:53:5)
>#1      HasuraConnectBase.addHeader 
>package:hasura_connect/…/core/hasura_connect_base.dart:49
>#2      _MyHomePageState._incrementCounter 
>package:hasura_connect_test/main.dart:60
>#3      _InkResponseState._handleTap 
>package:flutter/…/material/ink_well.dart:706
>#4      _InkResponseState.build.<anonymous closure> 
>package:flutter/…/material/ink_well.dart:789
>...
>Handler: "onTap"
>Recognizer: TapGestureRecognizer#1e9ea
>    debugOwner: GestureDetector
>    state: ready
>    won arena
>    finalPosition: Offset(372.0, 849.0)
>    finalLocalPosition: Offset(30.0, 25.0)
>    button: 1
>    sent tap down
>═════════════════════════════════════════════════════════════>═══════════════════

## Important: If I use the HasuraConnect constructor and include the headers parameter, it works perfectly, but using the previous method doesn't.

I'll be using this approach for now:

```dart
String query = "query MyQuery {company {name}}";
HasuraConnect connect = HasuraConnect('http://localhost:8080/v1/graphql' headers: {
      'x-hasura-admin-secret': 'secret'
});
connect.query(query).then((results) {
  print(results);
});
```

Maybe initializing this propery (i.e: headers = {}) at this following line should fix the problem:

https://github.com/Flutterando/hasura_connect/blob/4876aebf9a3f39ebbf7185bf2b75f6debc40ef44/lib/src/core/hasura_connect_base.dart#L17

**Comment by natarajnattu** [comment]
Hi @blinkn ,

Try like this:

```
var headers = {"x-hasura-admin-secret": "-----------secret------------"};
String query = "query MyQuery {company {name}}";
String url = 'http://localhost:8080/v1/graphql';
HasuraConnect hasuraConnect = HasuraConnect(url, headers: headers);
var r = await hasuraConnect.query(query);
```

:)

**Comment by blinkn** [comment]
Hi @natarajnattu , this is the exactly solution I posted on the end of my opened issue, using the headers in the constructor works fine, but using addHeader() doesn't.

**Comment by jacobaraujo7** [comment]
it´s a bug. I will create a PR

**Comment by paulobreim** [comment]
Também encontrei o mesmo erro.
