### ISSUE TITLE
Falta melhorar o aviso de erros de conexão.

### ISSUE THREAD

**Issue by hbedford** [Flutterando/hasura_connect#26]
Para ficar mais pratico ainda, coloque para alertar os erros de conexão que ocorrem, tive q colocar 1 print dentro do catcherror, pois não era possivel visualizar no catcherror do future;

**Comment by paulobreim** [comment]
Se o site não estiver no ar, ou se houve falha de chave o retorno de erro catch é igual:
 "HasuraError: connection error"
Precisa colocar a mensagem certa
