### ISSUE TITLE
Adicionar método ou atributo para alterar o header

### ISSUE THREAD

**Issue by Nanow** [Flutterando/hasura_connect#3]
O hasura possuí o **x-hasura-role** como atributo de header, para definir qual a role que está sendo utilizada entre as allowed-roles no jwt, a lib já possibilita alterar o header?

**Comment by jacobaraujo7** [comment]
Adicionado opção de headers via instancia e métodos addHeader, removeHeader e removeAllHeader na versão 0.0.7
Obrigado por informar :)
