### ISSUE TITLE
Pull more data and cache 

### ISSUE THREAD

**Issue by andrewpmoore** [Flutterando/hasura_connect#30]
Love the package and so simple to use compared to others.

One question though, if I grab some data with a limit/offset is there any way to concatenate the data from one result set to the next in the cache. 

If possible I'd love to avoid needing a backing database if I can use just the cache in the mobile app, but with long lists. Is there something similar to this https://pub.dev/packages/graphql_flutter#fetch-more-pagination

**Comment by rullyalves** [comment]
Como você imagina que esse recurso deva funcionar e qual a motivação ? Pra paginação comum do hasura isso faria sentido, visto que seria interessante concatenar com o cache anterior, agora pra subscriptions, a paginação funciona aumentando o limite de dados de X quantidade em X.
