### ISSUE TITLE
Converter retorno de Query em List<Model>

### ISSUE THREAD

**Issue by leonardomnds** [Flutterando/hasura_connect#34]
Olá pessoal. 

Estou tendo um problema para converter o retorno de uma Query, em uma lista de objetos. 
Meu método responsável pela conversão está dessa forma: 
![image](https://user-images.githubusercontent.com/22241101/74891403-b44d7980-5365-11ea-9a66-971cb4b2912a.png)

E estou tendo o seguinte erro:
![image](https://user-images.githubusercontent.com/22241101/74891464-df37cd80-5365-11ea-88c6-005ade37cc41.png)

O erro só ocorre quando tento a conversão usando o Json retornado na query (sem aspas).

> {
        id: 1,
        uf: PR,
        estado: Paraná
      }

Tentando a conversão com o Json retornado na interface do Hasura (com aspas), o erro não ocorre.
> {
        "id": 1,
        "uf": "PR",
        "estado": "Paraná"
      }

Existe alguma outra solução que eu possa utilizar para fazer essa conversão, mesmo que o Json retorne sem as aspas?

**Comment by Bwolfs2** [comment]
Eu sempre faço dessa forma:
``` dart
 static List<ProdutoModel> fromJsonList(List list) {
    if (list == null) return null;
    return list
        .map<ProdutoModel>((item) => ProdutoModel.fromMap(item))
        .toList();
```

**Comment by leonardomnds** [comment]
Resolvido.

Obrigado pelo auxílio @Bwolfs2. 

Eu ainda não tinha tentado passar para o método, o retorno da Query.toList().
