### ISSUE TITLE
Desktop flutter support

### ISSUE THREAD

**Issue by ReniDelonzek** [Flutterando/hasura_connect#35]
I really like the simplicity of this package, however, recently with the change from hive to shared preferences my app that has a management part that needs to run on the desktop has stopped working, because the plugin does not support it. Are there plans to re-offer desktop support?

**Comment by jacobaraujo7** [comment]
I'm thinking of using a LocalStorageDelegate and so using any service like the same hive. I'll also look at how the implementation of SharedPreferences for the desktop is going

**Comment by ReniDelonzek** [comment]
Hello, is there an update for this?

**Comment by jacobaraujo7** [comment]
Use LocalStorageDelegate in the new version of hasura_connect. Example: HiveLocalStorage()
