### ISSUE TITLE
Keep getting "Try again..." in logs after token expires

### ISSUE THREAD

**Issue by andrewpmoore** [Flutterando/hasura_connect#39]
I'm using firebase which uses tokens that expire after 1 hour.
In my code when going to make a call to hasura before making the call I check the expiry time of the token and will refresh it if it's about to expire.

That's all working fine.
My issue is that if I've got some subscriptions going and leave the app for an hour, I start getting "Try again..." repeated in the logs every 2 seconds.

Is this because the websockets fail once the token expires even though I've not made any direct calls to any new queries/mutations etc?

Can you think of a way to stop this happening?

**Comment by andrewpmoore** [comment]
for reference, I've ended up adding a WidgetsBindingObserver to stop listening to all streams when the app goes into the background and then set them up again when it resumes.

I've also put in a periodic timer while in the app that fires once every 55 minutes to obtain a new token and change the token in hasuraConnect

**Comment by arpitjacob** [comment]
Thanks I have the same issue, guess I'll have to do something similar. I wonder if there is a better solution

**Comment by arpitjacob** [comment]
Hi would you be able to elaborate how you solved it for the subscriptions, I am facing the same issue
