### ISSUE TITLE
Subscription returning wrong (cached) result.

### ISSUE THREAD

**Issue by kylesnipes** [Flutterando/hasura_connect#41]
I have a subscription that takes in an ID. The first time this subscription is made, the correct information is returned. Every subsequent time the subscription is made, it returns data matching the initial subscription, regardless if the ID has changed.

**Comment by andrewpmoore** [comment]
I found similar previous. I ended up doing this

snapshot?.cleanCache();
snapshot?.close();

before rerunning a query which seemed to help, but I'm not sure it 100% resolves it

**Comment by andrewpmoore** [comment]
I'm having similar problems, have you tried playing around passing a unique key into the subscription (there's an optional parameter for a key).

I do that, but then instead of getting back the old data, I'm now getting back no data on the 2nd call.

**Comment by andrewpmoore** [comment]
I've found out that I don't have this issue on version 1.1.2 of the package. It get's the correct data.

**Comment by andrewpmoore** [comment]
Has this been fixed or is there something we are doing wrong with the package?

**Comment by kylesnipes** [comment]
My issue ended up being the result of something else. Digging into it, the snapmap in HasuraConnectBase used for caching subscriptions uses a key based off the query only and does not include the variables. So if you attempt to subscribe to two queries differing only in variables, it'll always return the first one that was cached in snapmap.

**Comment by arpitjacob** [comment]
@kylesnipes could you explain this and give an example, I have the same issue, I am using a subscription to which I pass data and the variables change but only the first result is loaded every-time.

**Comment by kylesnipes** [comment]
@arpitjacob Let's say you have a simple query like 

`subscription GetThing($id: Int!) {
   id
}`

If you call subscribe with that query with the variables {'id': 0}, it'll successfully return what you expect. If however, you then call subscribe again with the same query but {'id': 1}, the subscription where id = 0 is returned because the client caches subscriptions based on query only. In this case, both subscriptions share a query but different variables. 

The subscriptions are wrapped in a class called SnapShot which allows you to dispose and change variables. There does not appear to be a way to successfully subscribe to a query twice with different variables though.

My workaround is to use something like

`subscription GetAllThings() {
   id
}`

and then using RxDart to split that stream into streams containing the individual things.

**Comment by arpitjacob** [comment]
@kylesnipes oh thank you so much, and thanks for the quick reply, I've been struggling with this the last 3 days, that makes so much sense I thought something was wrong with the way I was implementing Provider, StreamProvider. 

Unfortunately if I go with your approach it will load too much data, I need to load data based on a variable. 

So looks like this is a problem with the package.

**Comment by arpitjacob** [comment]
Ahhh I read through the documents again I missed this, I got it working now when I pass a different variable it updates the subscription.

`
Snapshot snapshot = hasuraConnect.subscription(docSubscription, variables: {"limit": 10});

//change values of variables for PAGINATIONS
snapshot.changeVariable({"limit": 20});
`

**Comment by happyfloat** [comment]
This needs to be documented better. Also it is really limiting to be able to only have one subscription at a time... I can not just subscribe to all my content... I should only do that for the content which is currently visible. I'm new to dart and flutter, so I'm not feeling confident enough to dig deeper into the lib and create a PR... maybe later then.

**Comment by acamenhas** [comment]
I also have this problem...
In my case I have 2 modules: employees and employee.
In the employees list when I click on an item, I pass the id as an argument and push the employee module to show his data (in a form) with this subscription:

```
  @override
  Stream<EmployeeModel> getEmployee(int id) {
    return connect.subscription(employeeQuery, variables: {"id": id}).map((json) {
      return EmployeeModel.fromJson(json['data']['employees'][0]);
    });
  }
```

When I pop and click on a new item, the new id as passed but the same employee data is showed.
I don't know if there's a problem with the dispose, or with the caching, if you can do a little demo you can see this problem happening.

If it's related with the package I think that's important to solve, because it's a feature that is used in various modules by everyone that works with subscriptions.

Thanks,
Artur
