### ISSUE TITLE
Erro apenas importando a package

### ISSUE THREAD

**Issue by j4cks0ndb** [Flutterando/hasura_connect#42]
Criei um projeto do zero sem mudar uma linha....
flutter create nome_projeto
slidy start
rodei o build la para gerar os .G
inclui o hasura_connect
quando apenas declaro a importação do package do hasura ja da erro

Compiler message:
/D:/src/flutter/.pub-cache/hosted/pub.dartlang.org/hasura_connect-1.2.0/lib/src/utils/hydrated.dart:6:7: Error: The non-abstract class 'HydratedSubject' is missing implementations for these members:
 - Subject.createForwardingController
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class HydratedSubject<T> extends Subject<T> implements ValueStream<T> {
      ^^^^^^^^^^^^^^^
/D:/src/flutter/.pub-cache/hosted/pub.dartlang.org/rxdart-0.24.0/lib/src/subjects/subject.dart:162:23: Context: 'Subject.createForwardingController' is defined here.
  StreamController<T> createForwardingController({
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^

![Capturar](https://user-images.githubusercontent.com/51239456/79399351-7fbb0000-7f59-11ea-9cca-5e9578dffb91.PNG)
![Capturar2](https://user-images.githubusercontent.com/51239456/79399377-92353980-7f59-11ea-8c43-a469071984cf.PNG)

**Comment by jacobaraujo7** [comment]
olá.
Vc tem uma instancia do rxdart mais recente no seu pc?

**Comment by j4cks0ndb** [comment]
> olá.
> Vc tem uma instancia do rxdart mais recente no seu pc?

Como verifico isso?

**Comment by jacobaraujo7** [comment]
tente usar
pub cache repair

**Comment by j4cks0ndb** [comment]
usei, mas continua mesmo erro, quanto ao rxdart durante o cache repair percebi que ele atualizou esses da imagem
![images](https://user-images.githubusercontent.com/51239456/79400872-e2ae9600-7f5d-11ea-9824-c0b357e783d4.png)

**Comment by jeffaknine** [comment]
I'm having the same issue, any fix ?

**Comment by franciscojader** [comment]
na versão mobile, ta funcionando normal, mas fazendo teste com um app web, tive o mesmo problema, para resolver, inserir no pubspec.yaml:
  rxdart: ^0.23.1

forçando ele trabalhar com esta versão, no meu caso resolveu.

**Comment by jeffaknine** [comment]
I'm still getting the issue. I'm running flutter 1.12.13+hotfix.9

**Comment by j4cks0ndb** [comment]
> na versão mobile, ta funcionando normal, mas fazendo teste com um app web, tive o mesmo problema, para resolver, inserir no pubspec.yaml:
> rxdart: ^0.23.1
> 
> forçando ele trabalhar com esta versão, no meu caso resolveu.

Consegui rodar fixando o rxdart na versão 0.23 também, mas no meu caso era apenas mobile e o erro acontece.

**Comment by jacobaraujo7** [comment]
Atualizei versão 1.2.1+1 corrige esse problema

**Comment by jacobaraujo7** [comment]
> mesmo problema aqui tanto pra web quanto no mobile.
> so baixando a versao do rxdart: ^0.23.1 que da certo mesmo
> 
> any fix?

Já foi corrigido na versao 1.2.1+1 do hasura_connect
