### ISSUE TITLE
I have a problema when my filter like have an accentuation

### ISSUE THREAD

**Issue by famadori** [Flutterando/hasura_connect#47]
When i put a filter with accentuation in connect.subscription(getAllQuery)  just doesn't respond and keeps trying and trying to loop

subscription getAllProduto {
  produto(where: {descricao: {_ilike: "%feijão%"}}, order_by: {descricao: asc}) {
    id
    descricao
  }
}

And when i put only _ilike: "%feij%" it´s work perfectly. Do you know what´s de problem?

**Comment by luizjunior05** [comment]
Any news about this bug?
