### ISSUE TITLE
Subscription - working with variables

### ISSUE THREAD

**Issue by acamenhas** [Flutterando/hasura_connect#48]
Hi all,

I cant put to work the subscriptions with variables.

I created the follow subscription, that its working on Graphiql:

![graphiql](https://user-images.githubusercontent.com/14015712/81875894-4934cd00-9579-11ea-818f-404cdba76841.png)

And write this flutter code:

```
String docSubscription = """
      subscription netideias_tasks($limit:Int!){
        netideias_tasks(limit: $limit) {
          id,
          title,
          estimated_minutes
        }
      }
    """;
```
```
hasuraConnect = HasuraConnect(url, headers: {'x-hasura-admin-secret': '...'});
Snapshot snapshot = hasuraConnect.subscription(docSubscription, variables: {"limit": 10});
```

And i'm getting the following error:

> HasuraError: not a valid graphql query
> 
> {type: complete, id: c3Vic2NyaXB0aW9ubmV0aWRlaWFzdGFza3MxMEludG5ldGlkZWlhc3Rhc2tzbGltaXQxMGlkdGl0bGVlc3RpbWF0ZWRtaW51dGVz}

If i remove the limit variable everything works great!

What i'm doing wrong?

Abraços!

**Comment by happyfloat** [comment]
I think you can remove the `subscription` prefix

**Comment by acamenhas** [comment]
I forgot to put \$limit on the variables.
Thanks!
