### ISSUE TITLE
Connection utilization

### ISSUE THREAD

**Issue by LeandroMoura3** [Flutterando/hasura_connect#51]
Hello,

I wanna have total control of the connections of hasura, but I don't understand how to connections works.

If I make a query in my server of hasura, this makes 2 or 4 connections, but I don't understand why.

Someone know what is it? How I can control these connections? I wanna only open a connection, make a query, and close it immediately. There run out of the purpose of the GraphQL hasura?

I very worry about free connections limitation of hasura. Someone have some experince about this here and wanna share here?

thank you!

**Comment by Bwolfs2** [comment]
The hasura connect make in theory just 1 connection.
Hasura has no connections Limit
