### ISSUE TITLE
Debug query

### ISSUE THREAD

**Issue by tallesdantas** [Flutterando/hasura_connect#52]
Hi guys, i'm trying to debug what kind of error hasura is returning in my query, but the hasura only returns "HasuraError: connection error" in my query, how can i see whats wrong with the query?

**Comment by drianoaz** [comment]
I have the same problem 😕

**Comment by evandrmb** [comment]
You could try your query in HasuraConsole, if it does have something wrong you will be able to see it. But as far as I'm concerned Connection Error is something related to your connection, maybe your device is without internet connection, maybe you're reaching the wrong end point, maybe you're not passing the authorization token, etc
