### ISSUE TITLE
Subscription - using variables - wrong result

### ISSUE THREAD

**Issue by acamenhas** [Flutterando/hasura_connect#57]
I also have this problem as other persons reported.
In my case I have 2 modules: employees and employee.
In the employees list when I click on an item, I pass the id as an argument and push the employee module to show his data (in a form) with this subscription:

```
  @override
  Stream<EmployeeModel> getEmployee(int id) {
    return connect.subscription(employeeQuery, variables: {"id": id}).map((json) {
      return EmployeeModel.fromJson(json['data']['employees'][0]);
    });
  }
```
When I pop and click on a new item, the new id as passed but the same employee data is showed.
I don't know if there's a problem with the dispose, or with the caching, if you do a little demo you can see this problem happening.

If it's related with the package I think that's important to solve, because it's a feature that is used in various modules by everyone that works with subscriptions.

![ezgif-3-1e32652acf9b](https://user-images.githubusercontent.com/14015712/83354065-a5a43480-a34e-11ea-8070-3ef9d6169caa.gif)

Thanks,
Artur

**Comment by clementyau** [comment]
+1
I ran into the same issue as well.

**Comment by clementyau** [comment]
Okay I debugged this. The root cause is line 109 of hasura_connect_base.dart:
    key = key ?? utils.generateBase(query);
It needs to generate the key not just from query but query + variables.

To work around the bug, you need to generate your own cache key and pass it into subscription calls.

cachedQuery has the same issue and similar workaround above applies.

**Comment by acamenhas** [comment]
@clementyau thank you for figuring it out!!
I hope that this helps the team to fix this more quickly!

**Comment by happyfloat** [comment]
Or for this use case you could also do something like this by calling `changeVariable`.
```
 Stream watchUsers({@required eventId}) {
    Snapshot snapshot = api.subscription(FETCH_EVENT_USERS, variables: {"id": eventId});

    // This is important here:
    return snapshot..changeVariable({"id": eventId});
  }
```

**Comment by acamenhas** [comment]
Hi @happyfloat thanks for your contribution to this topic!

I have 2 questions of your solution:
- "return snapshot..changeVariable({"id": eventId});" > don't return void()?
- and if it will not open 2 connections?

**Comment by happyfloat** [comment]
1. It will return the snapshot because of the `..`[cascade notation](https://dart.dev/guides/language/language-tour#cascade-notation-)

2. I hope not ...

This was basically a solution from another github issue here related to subscriptions.

**Comment by acamenhas** [comment]
I solved with:

```
    key = key ?? utils.generateBase(query);

    if(variables != null) {
      variables.keys.forEach((_keyvar) {
        key += _keyvar + '=' + variables[_keyvar].toString();
      });
```

both in subscription and cachedQuery functions.

Lets what for a "cleaner solution" that solved this issue.

**Comment by Bwolfs2** [comment]
Are u using Modular? Is yes u can set the singlethon=false on Binding ur PageController

**Comment by acamenhas** [comment]
> Are u using Modular? Is yes u can set the singlethon=false on Binding ur PageController

Thanks for your reply!
I do what you said, but don't worked:

```
  @override
  List<Bind> get binds => [
    Bind((i) => EmployeeController( i.get() )),
    Bind<IEmployeesRepository>((i) => EmployeeRepository(i.get()), singleton: false)
  ];
```

```
class EmployeeRepository implements IEmployeesRepository {
  final HasuraConnect connect;

  EmployeeRepository(this.connect);

  @override
  Stream<List<EmployeeModel>> getEmployees() {
    return connect.subscription(employeesQuery).map((item) {
      return (item['data']['project_employees'] as List).map((json) {
        return EmployeeModel.fromJson(json);
      }).toList();
    });
  }

  @override
  Stream<EmployeeModel> getEmployee(int id) {
    return connect.subscription(employeeQuery, variables: {"id": id}).map((json) {
      return EmployeeModel.fromJson(json['data']['project_employees'][0]);
    });
  }
}
```

**Comment by kylesnipes** [comment]
This is what some of us also noticed and reported #41

**Comment by Bwolfs2** [comment]
We add one example on example folder using changeVariables and is working fine, i guess u will need to verify if u are not create more then one Snapshot
