### ISSUE TITLE
Is JsonB column supported?

### ISSUE THREAD

**Issue by clementyau** [Flutterando/hasura_connect#58]
Hello thanks for this great library.

When using a Subscription with a JsonB column, it throws error

field (name) not found in type (table name)

Is JsonB column supported in hasura_connect? The same subscription query worked in GraphiQL console.

Thanks!

**Comment by andrewpmoore** [comment]
I'm using jsonb columns fine in my app with subscriptions, so it should work. Maybe show some code.
