### ISSUE TITLE
Application first offline

### ISSUE THREAD

**Issue by JErazo7** [Flutterando/hasura_connect#61]
First of all, we would like to thank you for the excellent package that makes integration with hasura easy. 

In my case I want to develop an application first offline. Is it possible to achieve this with this package? 

It is expected that offline mutations can persist so that they can be executed when the device is back online, and also to perform queries with the data I have stored in cache. In conclusion, achieve the offline functionality that has cloud firestore. 

Looking forward to your response, thank you very much.

**Comment by evandrmb** [comment]
It's possible. You could use Floor for offline persistence and each table could have a field called sync. So you could create a listener in your home so when the app is online select from Floor all registers that aren't synced and generate mutations for them.

**Comment by Bwolfs2** [comment]
I guess u can use hasura_cache_interceptor to create ur implementation. We have a query cache using https://pub.dev/packages/hive_cache_interceptor
