### ISSUE TITLE
WebSocketException: Connection to 'https://<domain>.com:0/hasura/v1/graphql#' was not upgraded to websocket

### ISSUE THREAD

**Issue by sharad-paghadal** [Flutterando/hasura_connect#62]
Query and mutation are working perfectly, but when it comes to subscription - it throws this error on console.

**Comment by sharad-paghadal** [comment]
I found temporary solution!

Issue:
- My hasura is deployed using docker and that is serving by nginx to add https.
- So my hasura connection url will be like -`https://mydomain.com/hasura/v1/graphql`
- In this case it takes 0 as a port, that is causing this issue.

Solution:
- Using url `https://mydomain.com:<PORT_USED_BY_DOCKER>/hasura/v1/graphql` fixed the issue.

This is temporary solution, some one please help me to fix it permanently.
Thanks.

**Comment by jeet-ardeshna-stl** [comment]
I was facing the same issue, but I solved it by removing a trailing '/' from the URL. ( '.../graphql/' to '.../graphql')

**Comment by raphaelbarbosaqwerty** [comment]
@sharad-paghadal Hi! What is your back-end? Actually, I got the same problem with Nginx, I found the solution in this [Issue](https://github.com/socketio/socket.io/issues/1942#issuecomment-82352072)
