### ISSUE TITLE
Is this project Dead?

### ISSUE THREAD

**Issue by arpitjacob** [Flutterando/hasura_connect#68]
I see someone else has created a fork and the developers don't seem to be responding here.

**Comment by Bwolfs2** [comment]
Sorry, we’ve been working hard for the past few days, but the package isn’t dead don’t use it in almost all of our projects

**Comment by arpitjacob** [comment]
No worries, thanks @Bwolfs2

**Comment by arpitjacob** [comment]
Hey Guys any updates
