### ISSUE TITLE
Support for GetX

### ISSUE THREAD

**Issue by gdelgado11** [Flutterando/hasura_connect#69]
GetX is an extra-light and powerful solution for Flutter. It combines high performance state management, intelligent dependency injection, and route management in a quick and practical way.
I think it is important to have tutorials on how to use hasura connect with provider, Bloc or GetX for the less expert or that we are just starting out in Flutter.

**Comment by gdelgado11** [comment]
Do you plan to include Getx Pattern?

**Comment by Bwolfs2** [comment]
You can use the state management you want, hasura_connect is agnostic to that
