### ISSUE TITLE
Connection Refuse

### ISSUE THREAD

**Issue by JacquesMarques** [Flutterando/hasura_connect#7]
Hi,
I try using this plugin with a Docker container on localhost, but when I try connect to Hasura I receive an error message like this:

I/flutter ( 3258): SocketException: OS Error: Connection refused, errno = 111, address = localhost, port = 37136

This occur when I execute:

`HasuraConnect('http://localhost:8080/v1/graphql');`

The Hasura console is running on localhost port 8080 but I cant connect in it,[

Anybody know how fix this?

Thanks

**Comment by patelmanjeet** [comment]
use 10.0.2.2  instead of localhost

`HasuraConnect('http://10.0.2.2:8080/v1/graphql');`
