### ISSUE TITLE
removed support for `cachedQuery`?

### ISSUE THREAD

**Issue by sharad-paghadal** [Flutterando/hasura_connect#73]
I was using v1.2.2 previously and `cachedQuery` was working perfectly for me. But with v2.0.0, I get an error for using `cachedQuery`, and surprisingly I don't see any alternatives for that too.

Can someone explain me how to use the same feature with new version?

**Comment by sharad-paghadal** [comment]
Updated README for how to use the alternative method. Thanks!

**Comment by arpitjacob** [comment]
@sharad-paghadal could you tell me what the solution is?

**Comment by excogitatr** [comment]
@sharad-paghadal could you share us how to do that.
