### ISSUE TITLE
Poor Documentation and Support

### ISSUE THREAD

**Issue by arpitjacob** [Flutterando/hasura_connect#75]
Hey guys, I've tried upgrading to 2.0, but the documentation is poor and I don't see any response to current open issues by the developers. I understand this is an open source project, but a list of breaking changes and examples of how to fix them would be really helpful.

For example this line of code the function **changeVariable** 
`snapshot.changeVariable({"limit": 20});`

has changed to  **changeVariables** its such a small change thats its hardly noticeable 
`snapshot.changeVariables({"limit": 20});`

subscription which returned a stream before need to be awaited which breaks a lot of code
`await hasuraConnect.subscription` 
an example function that returns a stream would be helpful. 

The big change is  **interceptors** but there are no examples explaining how we should replace `cleanCache` & `cachedQuery`?

**Comment by arpitjacob** [comment]
the functions and variable have no documentations so it hard to figure out unless I dive deep into the code to see whats happening.

**Comment by Bwolfs2** [comment]
We will fix it and i believe this will not happend again
