### ISSUE TITLE
Example's code is inconsistent

### ISSUE THREAD

**Issue by Ascenio** [Flutterando/hasura_connect#78]
The example code of the lib should demonstrate funcionality while following common guidelines and good practices. 
The model `ProdutoDto` should be in english but it's in portuguese, as well as the methods of `AddProdutoRepository` (getProduto(), addproduto(), etc.)
Besides, naming the `AddProdutoRepository` as such is misleading. The repo is not limited to add products, but also returns subscriptions and gets data.

**Comment by Ascenio** [comment]
I just noticed that the example code doesn't even run. There's no main.

**Comment by Bwolfs2** [comment]
Here u have a full implementation source:
https://github.com/Bwolfs2/loja_hasura

Sorry for the example code, but is Just a sample not a implementation =/

**Comment by Ascenio** [comment]
But as any other lib, there should be an example folder with a functional app. Doesn't need to be complex, just to show the basics. If there isn't, then it's the same as just having the docs.
