### ISSUE TITLE
Nova implementação da subscription

### ISSUE THREAD

**Issue by carlos-cnds** [Flutterando/hasura_connect#80]
Qual widget do flutter utilizar para o Future Snapshot da nova versão do subscription? 
Na versão anterior 1.2.2+1, dava pra utilizar o StreamBuilder de bôa.

**Comment by Bwolfs2** [comment]
The same, u just need to use Await when u call ur snapshot function:
Here a sample Project:
https://github.com/Bwolfs2/loja_hasura

https://github.com/Bwolfs2/loja_hasura/blob/master/lib/app/modules/home/repositories/home_repository.dart
