### ISSUE TITLE
how to decode in utf-8 the data returned by query ?

### ISSUE THREAD

**Issue by mandreshope** [Flutterando/hasura_connect#81]

**Comment by Bwolfs2** [comment]
The result is not utf-8? I never have this problem =/

**Comment by Mandreshope** [comment]
Yes,
 
![image](https://user-images.githubusercontent.com/46576627/99989649-ec398f80-2dc3-11eb-8685-ea6895bea11a.png)

For utf-8 converter, I make an extension

```DART
import 'dart:convert';

extension Utf8convert on String {
  String  _utf8convert() {
    List<int> bytes = this.toString().codeUnits;
    return utf8.decode(bytes);
  }
  String get utf8convert => _utf8convert();
}
```

**Comment by Bwolfs2** [comment]
Add to a documentation as a possible problema Solution
