### ISSUE TITLE
Unhandled Exception: HasuraRequestError: unexpected variables in variableValues: name

### ISSUE THREAD

**Issue by ramsmart-inno** [Flutterando/hasura_connect#89]
I couldn't move further. Everything is configured as mention.

**Comment by evandrmb** [comment]
Could you show the code of your query?

**Comment by ramsmart-inno** [comment]
Now it's working perfectly. I am previously tried the general Hasura which hosted on heroku, once i replaced the hasura cloud2.0 query it asks for header validation to process secure API request.

But how to handle the json caching in hasura connect?

**Comment by Bwolfs2** [comment]
U can create ur own implementation of https://pub.dev/packages/hasura_cache_interceptor or use https://pub.dev/packages/shared_preferences_cache_interceptor
