### ISSUE TITLE
Unhanbled Exception: Bad state: Cannot add new events after calling close

### ISSUE THREAD

**Issue by moaberdan** [Flutterando/hasura_connect#9]
Bom tarde, estou utilizando hasura_connect para estabelecer uma subscription ao Hasura. 

Configurei o HasuraConnect para ser injetado nas dependências do app.module. 

Criei também um Repository que recebe o HasuraService (criado por mim que só armazena uma instância do HasuraConnect) onde eu recupero a instância do HasuraConnect.  

app.module (dependências)
![Captura de Tela_selecionar área_20191119144514](https://user-images.githubusercontent.com/4240026/69171820-6cefec80-0adb-11ea-9f76-cd7da9134404.png)

HasuraService
![Captura de Tela_selecionar área_20191119144629](https://user-images.githubusercontent.com/4240026/69171851-7c6f3580-0adb-11ea-9ed5-205cc718f37f.png)

Chamando o subscription no repository
![Captura de Tela_selecionar área_20191119144933](https://user-images.githubusercontent.com/4240026/69172054-e25bbd00-0adb-11ea-950d-0c0a7cf0e57c.png)

A chamada no bloc
![Captura de Tela_selecionar área_20191119145100](https://user-images.githubusercontent.com/4240026/69172135-0ae3b700-0adc-11ea-8963-233cc55e8c5c.png)

Implementei as minas páginas para ficar ouvindo as subscription via bloc somente quando a mesma estivesse ativa (o bloc da um close no snapshot ativo para aquela conexão), mas quando a página é fechada e aberta novamente ocorre uma exceção que pode ser visto na imagem.

![Captura de Tela_selecionar área_20191119144159](https://user-images.githubusercontent.com/4240026/69171467-c3106000-0ada-11ea-8968-86fcff1e3f49.png)

**Comment by jacobaraujo7** [comment]
Estou simulando aqui, mas ao que parece é um bug. Estando corrigido já informo.

**Comment by jacobaraujo7** [comment]
O erro está quando fecha o Snapshot Ele acaba fechando a stream da conexão.
Obrigado pelo feedback, estou trabalhando na correção.

**Comment by jacobaraujo7** [comment]
Por favor, teste a versão 0.1.3

**Comment by moaberdan** [comment]
Erro corrigido, obrigado pela atenção, Jacob.
