### ISSUE TITLE
open source hasura

### ISSUE THREAD

**Issue by gerardwebb** [Flutterando/hasura_connect#95]
Is anyone interested in a open source golang backend that replaces hasura ?

hasara connects to postresql using CDC, and thats pretty easy stuff.
then there is the subscriptions, which is a change feed off the CDC of a table change.

**Comment by barbalex** [comment]
Isn't hasura open source itself?

**Comment by tauamendonca** [comment]
Not an issue with Hasura_connect, can we close it? @jacobaraujo7
