### ISSUE TITLE
invalid url for websocket connection in dev environment

### ISSUE THREAD

**Issue by barbalex** [Flutterando/hasura_connect#96]
I am trying to connect to a local hasura instance as described here: https://hasura.io/docs/latest/graphql/core/deployment/deployment-guides/docker.html#deployment-docker. I work on Windows 10.

My code:
```dart
HasuraConnect wsConnect = HasuraConnect(wsGraphQlUri);
Snapshot snapshot = await wsConnect.subscription('''
  subscription allDataSubscription {
    projects {
      id
      label
      name
      account_id
    }
  }
  ''');
```
The error:
```
InvalidRequestError (InvalidRequestError: Invalid url)
```

I had the same error for regular queries:
```dart
HasuraConnect gqlConnect = HasuraConnect(graphQlUri);
var r = await gqlConnect.query('''
  query allDataSubscription {
    projects {
      id
      label
      name
      account_id
    }
  }
  ''');
```
resulted in the same error when I passed in `'http://0.0.0.0:8080/v1/graphql'` as graphQlUri. It works now when I pass in the magic `'http://10.0.2.2:8080/v1/graphql'` value instead as mentioned here: 'http://10.0.2.2:8080/v1/graphql'

I tried these version for wsGraphQlUri:
- 'ws://localhost:8080/v1/graphql'
- 'ws://0.0.0.0:8080/v1/graphql'
- 'ws://10.0.2.2:8080/v1/graphql'

**Comment by Bwolfs2** [comment]
I can't simulate.
I know "Magic Ip" http://10.0.2.2:8080 works in the emulator, but I don't understand what the error itself is.
If the error still persists, please open the issue.
